package model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Anexo generated by hbm2java
 */
@Entity
@Table(name = "anexo")
public class Anexo  implements java.io.Serializable {

    @Id
    @Column(name="cdanexo", unique=true, nullable=false)
     private int cdanexo;
    
    @Column(name = "url")
     private String url;
    
    @Column(name = "nome")
     private String nome;
    
    @Column(name = "tipo")
     private String tipo;
    
 //    private Set anexoses = new HashSet(0);

    public Anexo() {
    }

	
    public Anexo(int cdanexo) {
        this.cdanexo = cdanexo;
    }
    public Anexo(int cdanexo, String url, String nome, String tipo, Set anexoses) {
       this.cdanexo = cdanexo;
       this.url = url;
       this.nome = nome;
       this.tipo = tipo;
       //this.anexoses = anexoses;
    }
   
    public int getCdanexo() {
        return this.cdanexo;
    }
    
    public void setCdanexo(int cdanexo) {
        this.cdanexo = cdanexo;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    /*
    public Set getAnexoses() {
        return this.anexoses;
    }
    
    public void setAnexoses(Set anexoses) {
        this.anexoses = anexoses;
    }*/




}


