package model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 * Anexos generated by hbm2java
 */
@Entity
@Table(name = "Anexos")
public class Anexos  implements java.io.Serializable {

    @Id
    @Column(name="id", unique=true, nullable=false)
     private AnexosId id;
    
    @Column(name = "anexo")
     private Anexo anexo;
   
    @ManyToOne
    @JoinColumn(name = "cdduvida")
     private Duvida duvida;

    public Anexos() {
    }

	
    public Anexos(AnexosId id) {
        this.id = id;
    }
    public Anexos(AnexosId id, Anexo anexo, Duvida duvida) {
       this.id = id;
       this.anexo = anexo;
       this.duvida = duvida;
    }
   
    public AnexosId getId() {
        return this.id;
    }
    
    public void setId(AnexosId id) {
        this.id = id;
    }
    public Anexo getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(Anexo anexo) {
        this.anexo = anexo;
    }
    public Duvida getDuvida() {
        return this.duvida;
    }
    
    public void setDuvida(Duvida duvida) {
        this.duvida = duvida;
    }




}


