package model;
// Generated 01/11/2016 17:06:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 * Disciplina generated by hbm2java
 */
@Entity
@Table(name = "Disciplina")
public class Disciplina  implements java.io.Serializable {

    @Id
    @Column(name ="cdDisciplina", unique=true, nullable=false)
     private int cddisciplina;
    
    @Column(name="nome")
     private String nome;
    
    // private Set materias = new HashSet(0);

    public Disciplina() {
    }

	
    public Disciplina(int cddisciplina) {
        this.cddisciplina = cddisciplina;
    }
    public Disciplina(int cddisciplina, String nome, Set materias) {
       this.cddisciplina = cddisciplina;
       this.nome = nome;
     //  this.materias = materias;
    }

   
    public int getCddisciplina() {
        return this.cddisciplina;
    }
    
    public void setCddisciplina(int cddisciplina) {
        this.cddisciplina = cddisciplina;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    /*public Set getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Set materias) {
        this.materias = materias;
    }*/




}


