package model;
// Generated 01/11/2016 17:06:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 * Duvida generated by hbm2java
 */
@Entity
@Table(name = "Duvida")
public class Duvida  implements java.io.Serializable {

    @Id
    @Column(name ="cdduvida", unique=true, nullable=false)
     private int cdduvida;
      
    @ManyToOne
    @JoinColumn(name = "cdmateria")
     private Materia materia;
     
    @ManyToOne
    @JoinColumn(name = "cdusuario")
     private Usuario usuario;
    
    @Column(name="conteudo")
     private String conteudo;
    
    @Column(name="Data")
     private Date data;
    // private Set anexoses = new HashSet(0);

    public Duvida() {
    }

	
    public Duvida(int cdduvida) {
        this.cdduvida = cdduvida;
    }
    public Duvida(int cdduvida, Materia materia, Usuario usuario, String conteudo, Date data) {
       this.cdduvida = cdduvida;
       this.materia = materia;
       this.usuario = usuario;
       this.conteudo = conteudo;
       this.data = data;
       //this.anexoses = anexoses;
    }
   
    public int getCdduvida() {
        return this.cdduvida;
    }
    
    public void setCdduvida(int cdduvida) {
        this.cdduvida = cdduvida;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getConteudo() {
        return this.conteudo;
    }
    
    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
   
    //public Anexos getAnexoses() {
    //    return this.anexoses;
    //}
    
    //public void setAnexoses(Anexos anexoses) {
    //    this.anexoses = anexoses;
    //}




}


