package model;
// Generated 01/11/2016 17:06:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 * Mensagem generated by hbm2java
 */

@Entity
@Table(name = "Mensagem")
public class Mensagem  implements java.io.Serializable {

    @Id
    @Column(name="idMsg", unique=true, nullable=false)
     private int idMsg;
    
    @Column(name= "nomeUsu")
     private String nomeUsu;
    @Column(name= "mensagem")
     private String mensagem;

    public Mensagem() {
    }

	
    public Mensagem(int idMsg) {
        this.idMsg = idMsg;
    }
    public Mensagem(int idMsg, String nomeUsu, String mensagem) {
       this.idMsg = idMsg;
       this.nomeUsu = nomeUsu;
       this.mensagem = mensagem;
    }
   
    public int getIdMsg() {
        return this.idMsg;
    }
    
    public void setIdMsg(int idMsg) {
        this.idMsg = idMsg;
    }
    public String getNomeUsu() {
        return this.nomeUsu;
    }
    
    public void setNomeUsu(String nomeUsu) {
        this.nomeUsu = nomeUsu;
    }
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }




}


