package model;
// Generated 01/11/2016 17:06:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 * PubliMateriaId generated by hbm2java
 */
@Entity
@Table(name = "PubliMateriaId")
public class PubliMateriaId  implements java.io.Serializable {

    @ManyToOne
    @JoinColumn(name = "cdMateria")
     private Integer cdmateria;
    
     @ManyToOne
    @JoinColumn(name = "cdpublicadao")
     private Integer cdpublicacao;
     
    @Id
    @Column(name="idpm", unique=true, nullable=false)
    private Long idpm;
  

    public PubliMateriaId() {
    }

    public PubliMateriaId(Integer cdmateria, Integer cdpublicacao) {
       this.cdmateria = cdmateria;
       this.cdpublicacao = cdpublicacao;
    }
   
    public Integer getCdmateria() {
        return this.cdmateria;
    }
    
    public void setCdmateria(Integer cdmateria) {
        this.cdmateria = cdmateria;
    }
    public Integer getCdpublicacao() {
        return this.cdpublicacao;
    }
    
    public void setCdpublicacao(Integer cdpublicacao) {
        this.cdpublicacao = cdpublicacao;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PubliMateriaId) ) return false;
		 PubliMateriaId castOther = ( PubliMateriaId ) other; 
         
		 return ( (this.getCdmateria()==castOther.getCdmateria()) || ( this.getCdmateria()!=null && castOther.getCdmateria()!=null && this.getCdmateria().equals(castOther.getCdmateria()) ) )
 && ( (this.getCdpublicacao()==castOther.getCdpublicacao()) || ( this.getCdpublicacao()!=null && castOther.getCdpublicacao()!=null && this.getCdpublicacao().equals(castOther.getCdpublicacao()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCdmateria() == null ? 0 : this.getCdmateria().hashCode() );
         result = 37 * result + ( getCdpublicacao() == null ? 0 : this.getCdpublicacao().hashCode() );
         return result;
   }   

    public Long getIdpm() {
        return idpm;
    }

    public void setIdpm(Long idpm) {
        this.idpm = idpm;
    }



}


