package model;
// Generated 01/11/2016 17:06:20 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;




/**
 * SegueMateriaId generated by hbm2java
 */
@Entity
@Table(name = "SegueMateriaId")
public class SegueMateriaId  implements java.io.Serializable {

   @ManyToOne
   @JoinColumn(name = "cdusuario")
     private Integer cdusuario;
   
   @ManyToOne
   @JoinColumn(name = "cdMateria")
     private Integer cdmateria;

    public SegueMateriaId() {
    }

    public SegueMateriaId(Integer cdusuario, Integer cdmateria) {
       this.cdusuario = cdusuario;
       this.cdmateria = cdmateria;
    }
   
    public Integer getCdusuario() {
        return this.cdusuario;
    }
    
    public void setCdusuario(Integer cdusuario) {
        this.cdusuario = cdusuario;
    }
    public Integer getCdmateria() {
        return this.cdmateria;
    }
    
    public void setCdmateria(Integer cdmateria) {
        this.cdmateria = cdmateria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SegueMateriaId) ) return false;
		 SegueMateriaId castOther = ( SegueMateriaId ) other; 
         
		 return ( (this.getCdusuario()==castOther.getCdusuario()) || ( this.getCdusuario()!=null && castOther.getCdusuario()!=null && this.getCdusuario().equals(castOther.getCdusuario()) ) )
 && ( (this.getCdmateria()==castOther.getCdmateria()) || ( this.getCdmateria()!=null && castOther.getCdmateria()!=null && this.getCdmateria().equals(castOther.getCdmateria()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCdusuario() == null ? 0 : this.getCdusuario().hashCode() );
         result = 37 * result + ( getCdmateria() == null ? 0 : this.getCdmateria().hashCode() );
         return result;
   }   


}


